### ISSUE TITLE
java.io.EOFException 03-14 09:39:14.077: W/System.err(5935):     at libcore.io.Streams.readAsciiLine(Streams.java:203)

### ISSUE THREAD

**Issue by andot** [hprose/hprose-java#12]
我们在开发手机移动端的时候，在andriod4.0版本上，不断出现以下错误，困扰了我们很久：
 java.io.EOFException
03-14 09:39:14.077: W/System.err(5935):     at libcore.io.Streams.readAsciiLine(Streams.java:203)
03-14 09:39:14.077: W/System.err(5935):     at libcore.net.http.HttpEngine.readResponseHeaders(HttpEngine.java:573)
03-14 09:39:14.077: W/System.err(5935):     at libcore.net.http.HttpEngine.readResponse(HttpEngine.java:821)
03-14 09:39:14.077: W/System.err(5935):     at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:283)
03-14 09:50:46.547: W/System.err(6476):     at libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:177)
03-14 09:50:46.547: W/System.err(6476):     at libcore.net.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:271)
经过搜查，需要以下设置
if (Build.VERSION.SDK != null&& Build.VERSION.SDK_INT > 13) {
urlConnect.setRequestProperty("Connection", "close");
}
见http://stackoverflow.com/questions/15411213/android-httpsurlconnection-eofexception
咱们hporse 的java客户端，可以通过HproseHttpClient.setHeader("Connection", "close")进行urlConnect属性指定，但是查看源代码发现，
对于“Connection”属性，设置不起作用。
我手工修改了源代码，设置了以上参数后，上面错误不再出现，希望新版本能支持！

**Comment by andot** [comment]
如果是服务器不支持 keepAlive 特征的话，那只需要设置一下：
```
client.setKeepAlive(false);
```
就可以了。
