### ISSUE TITLE
java.lang.NoSuchMethodError: Can't find this method getUser

### ISSUE THREAD

**Issue by hank-whu** [hprose/hprose-java#28]
```java
public class User implements Serializable {
	private static final long serialVersionUID = 2566816725396650300L;

	private long id;
	private String name;
	private int sex;
	private LocalDate birthday;
	private List<Integer> permissions;
	private int status;
	private LocalDateTime createTime;
	
	//getters and setters ...
}
```
```java
public interface UserService {
	public boolean existUser(String email);
	public boolean createUser(User user);
	public User getUser(long id);
	public Page<User> listUser(int pageNo);
}
```
```java
Exception in thread "main" java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy0.getUser(Unknown Source)
	at benchmark.rpc.Client.main(Client.java:84)
Caused by: java.util.concurrent.ExecutionException: hprose.common.HproseException: java.lang.NoSuchMethodError: Can't find this method getUser
	at hprose.util.concurrent.PromiseFuture.get(PromiseFuture.java:82)
	at hprose.client.HproseClient.invoke(HproseClient.java:731)
	at hprose.client.HproseClient.invoke(HproseClient.java:695)
	at hprose.client.HproseInvocationHandler.invoke(HproseInvocationHandler.java:165)
	... 2 more
```

**Comment by hank-whu** [comment]
<version.hprose>2.0.35</version.hprose>

**Comment by andot** [comment]
Do you publish getUser method on your hprose server?

**Comment by danielsawan** [comment]
the method you call have to be static...

**Comment by hank-whu** [comment]
@danielsawan 
yes, it works, thanks
